### ISSUE TITLE
Path is not set for cookie storage

### ISSUE THREAD

**Issue by bisubus** [MikaAK/angular2-locker#17]
In current implementation the path isn't specified, this causes it to be figured out by browser. It is not compatible with HTML5 mode routing and PathLocationStrategy.

I had a weird bug where 'deleting cookies' recipe really helped at last. As it appeared, were two cookies with same namespaces and names, one for `/` path, another for `/route` path.

It is not possible to specify custom config for driver. I guess it may be set to base href by user, but it should be `/` by default.

**Comment by MikaAK** [comment]
I've not had a problem with PathLocationStrategy and using this. There are plans to open up config but I haven't had time

**Comment by bisubus** [comment]
Ok, I've switched to local storage driver for now but I will consider to PR if I will happen to use cookies once more.

I'm not even sure what exactly happened, but without cookie path being set explicitly, a cookie from one path/route shadowed a cookie from another path/route, this resulted in having read-only cookie.
