### ISSUE TITLE
Cannot use this to build Ionic2 APP

### ISSUE THREAD

**Issue by Marcnuth** [MikaAK/angular2-locker#20]
I create an Ionic2 APP, and import this into it.

Then I tried to build the APP for android platform, it will show error when building 

[23:22:20]  Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider 
            replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in 
            /Users/abc/code/ionic2/test/.tmp/app/app.module.ts, resolving symbol AppModule in 
            /Users/abc/code/ionic2/test/.tmp/app/app.module.ts 
[23:22:20]  ngc failed 
[23:22:20]  ionic-app-script task: "build" 
[23:22:20]  Error: Error

**Comment by MikaAK** [comment]
Iconic config issue, not issue with this lib
