### ISSUE TITLE
Memory Storage ts error

### ISSUE THREAD

**Issue by digitalcraftco** [MikaAK/angular2-locker#6]
`src/js/storage/MemoryStorage.ts(8,19): error TS2495: Type 'Iterator<{}>' is not an array type or a string type.`

Looks like this is culprit. 

`for (let key of _cache.keys())`

2.0.0-beta.17

**Comment by MikaAK** [comment]
I haven't had time to check this out in beta.17 yet. Due to lack of time I'm most likely gonna skip beta.17 and just update straight to `rc-1` unless anyone has a reason!

**Comment by digitalcraftco** [comment]
Sounds like a good idea to me.
