### ISSUE TITLE
Plan for upgrading angular2 rc dependencies?

### ISSUE THREAD

**Issue by pccwanselm** [MikaAK/angular2-locker#7]
Hi,

Currently the dependencies is pointing to the beta, by chance is there any plan that will migrate to @angular rc version soon?

Thanks,
Anselm

**Comment by MikaAK** [comment]
Yep, that's the plan, no time right now but I will do it on saturday or sunday. I already started it last weekends but ran into some complications with the new setup, I'll keep this open till I update

**Comment by pccwanselm** [comment]
Thanks for the news and your great work.

Looking forward to your next release.

**Comment by MikaAK** [comment]
Released 0.3.0
